version: "3"
services:
  postgres:
    container_name: db-atv2
    image: carlos/db-atv2
    build: ./postgres
    ports:
     - "5434:5432"
  web:
    container_name: app-atv2
    build: ./dois
    image: carlos/app-atv2
    depends_on: 
    - "postgres"
    ports:
     - "8082:8080"
     - 4848 
     - 8009 
     - 9009 
     - 8181 
     - 3700
    links:
     - "postgres:host-banco"
